/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppStepsRouteImport } from './routes/_app/steps'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBodyRouteImport } from './routes/_app/body'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppRoutinesIndexRouteImport } from './routes/_app/routines/index'
import { Route as AppHistoryIndexRouteImport } from './routes/_app/history/index'
import { Route as AppExercisesIndexRouteImport } from './routes/_app/exercises/index'
import { Route as AppRoutinesNewRouteImport } from './routes/_app/routines/new'
import { Route as AppRoutinesRoutineIdRouteImport } from './routes/_app/routines/$routineId'
import { Route as AppExercisesExerciseIdRouteImport } from './routes/_app/exercises/$exerciseId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppStepsRoute = AppStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBodyRoute = AppBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesIndexRoute = AppRoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppExercisesIndexRoute = AppExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesNewRoute = AppRoutinesNewRouteImport.update({
  id: '/routines/new',
  path: '/routines/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoutineIdRoute = AppRoutinesRoutineIdRouteImport.update({
  id: '/routines/$routineId',
  path: '/routines/$routineId',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesExerciseIdRoute = AppExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/body': typeof AppBodyRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/plan': typeof AppPlanRoute
  '/plans': typeof AppPlansRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/steps': typeof AppStepsRoute
  '/today': typeof AppTodayRoute
  '/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/routines/$routineId': typeof AppRoutinesRoutineIdRoute
  '/routines/new': typeof AppRoutinesNewRoute
  '/exercises/': typeof AppExercisesIndexRoute
  '/history/': typeof AppHistoryIndexRoute
  '/routines/': typeof AppRoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/body': typeof AppBodyRoute
  '/dashboard': typeof AppDashboardRoute
  '/plan': typeof AppPlanRoute
  '/plans': typeof AppPlansRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/steps': typeof AppStepsRoute
  '/today': typeof AppTodayRoute
  '/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/routines/$routineId': typeof AppRoutinesRoutineIdRoute
  '/routines/new': typeof AppRoutinesNewRoute
  '/exercises': typeof AppExercisesIndexRoute
  '/history': typeof AppHistoryIndexRoute
  '/routines': typeof AppRoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/body': typeof AppBodyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRouteWithChildren
  '/_app/plan': typeof AppPlanRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/steps': typeof AppStepsRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/_app/routines/$routineId': typeof AppRoutinesRoutineIdRoute
  '/_app/routines/new': typeof AppRoutinesNewRoute
  '/_app/exercises/': typeof AppExercisesIndexRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/routines/': typeof AppRoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/body'
    | '/dashboard'
    | '/history'
    | '/plan'
    | '/plans'
    | '/profile'
    | '/settings'
    | '/steps'
    | '/today'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/routines/new'
    | '/exercises/'
    | '/history/'
    | '/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/body'
    | '/dashboard'
    | '/plan'
    | '/plans'
    | '/profile'
    | '/settings'
    | '/steps'
    | '/today'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/routines/new'
    | '/exercises'
    | '/history'
    | '/routines'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/body'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/plan'
    | '/_app/plans'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/steps'
    | '/_app/today'
    | '/_app/exercises/$exerciseId'
    | '/_app/routines/$routineId'
    | '/_app/routines/new'
    | '/_app/exercises/'
    | '/_app/history/'
    | '/_app/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/steps': {
      id: '/_app/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof AppStepsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/body': {
      id: '/_app/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AppBodyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/': {
      id: '/_app/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof AppRoutinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/exercises/': {
      id: '/_app/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AppExercisesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/new': {
      id: '/_app/routines/new'
      path: '/routines/new'
      fullPath: '/routines/new'
      preLoaderRoute: typeof AppRoutinesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/$routineId': {
      id: '/_app/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof AppRoutinesRoutineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/$exerciseId': {
      id: '/_app/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AppExercisesExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryIndexRoute: AppHistoryIndexRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBodyRoute: typeof AppBodyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppPlanRoute: typeof AppPlanRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStepsRoute: typeof AppStepsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppExercisesExerciseIdRoute: typeof AppExercisesExerciseIdRoute
  AppRoutinesRoutineIdRoute: typeof AppRoutinesRoutineIdRoute
  AppRoutinesNewRoute: typeof AppRoutinesNewRoute
  AppExercisesIndexRoute: typeof AppExercisesIndexRoute
  AppRoutinesIndexRoute: typeof AppRoutinesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBodyRoute: AppBodyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppPlanRoute: AppPlanRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStepsRoute: AppStepsRoute,
  AppTodayRoute: AppTodayRoute,
  AppExercisesExerciseIdRoute: AppExercisesExerciseIdRoute,
  AppRoutinesRoutineIdRoute: AppRoutinesRoutineIdRoute,
  AppRoutinesNewRoute: AppRoutinesNewRoute,
  AppExercisesIndexRoute: AppExercisesIndexRoute,
  AppRoutinesIndexRoute: AppRoutinesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
